name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ls /Applications
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_11.6.app
    - name: Test
      run: xcodebuild test -scheme MovableToolbarTests -configuration Debug -sdk iphonesimulator -destination 'name=iPhone 8'
